apiVersion: v1
kind: Service
metadata:
  name: deel
spec:
  selector:
    app: deel
  ports:
    - port: 80
      targetPort: 3001
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deel
  template:
    metadata:
      labels:
        app: deel
    spec:
      containers:
        - name: app
          image: deel/deel
          ports:
            - containerPort: 3001
          env:
            - name: DATABASE_URL
              value: postgres://postgres:password@pg:5432/postgres
          imagePullPolicy: Never