const swaggerAutogen = require('swagger-autogen')();

const doc = {
  info: {
    version: '1.0.0',
    title: 'Contracts API',
    description:
      'Documentation automatically generated by the <b>swagger-autogen</b> module.',
  },
};

const outputFile = '../swagger.json';
const endpointsFiles = ['../src/routes/*.js'];

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require('../src/app');
});
